"""Add score fields to Contract

Revision ID: cc0b6f9cfdcb
Revises: 46980a8e385c
Create Date: 2026-01-31 13:27:21.010996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0b6f9cfdcb'
down_revision = '46980a8e385c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('required_score', sa.Integer(), nullable=False))
    op.add_column('contracts', sa.Column('current_score', sa.Integer(), nullable=False))
    op.alter_column('contracts', 'ou_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'ou_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('contracts', 'current_score')
    op.drop_column('contracts', 'required_score')
    # ### end Alembic commands ###
