"""first migration

Revision ID: 46980a8e385c
Revises: 
Create Date: 2026-01-31 13:13:02.639356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46980a8e385c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_name', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('authority_score', sa.Integer(), nullable=False),
    sa.Column('security_policy_inside', sa.JSON(), nullable=True),
    sa.Column('security_policy_outside', sa.JSON(), nullable=True),
    sa.Column('alternate_policies', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('organization_units',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prime_field_hex', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_edges',
    sa.Column('from_group_id', sa.Uuid(), nullable=False),
    sa.Column('to_group_id', sa.Uuid(), nullable=False),
    sa.Column('is_self_loop', sa.Boolean(), nullable=False),
    sa.Column('ou_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['ou_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['to_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_schemes',
    sa.Column('ou_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('key_component_index', sa.Integer(), nullable=False),
    sa.Column('threshold_t', sa.Integer(), nullable=False),
    sa.Column('total_shares_w', sa.Integer(), nullable=False),
    sa.Column('polynomial_degree', sa.Integer(), nullable=False),
    sa.Column('network_type', sa.String(length=1), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['ou_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('encrypted_shares', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_table('contracts',
    sa.Column('contract_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ipfs_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('ou_id', sa.Uuid(), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ou_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('user_shares',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('threshold_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('share_x', sa.String(length=255), nullable=False),
    sa.Column('share_y', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['threshold_scheme_id'], ['threshold_schemes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('approver_group_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('share_x_revealed', sa.String(length=255), nullable=True),
    sa.Column('share_y_revealed', sa.String(length=255), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approver_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_requirements',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('required_group_name', sa.String(length=10), nullable=False),
    sa.Column('required_user_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['required_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signatures',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('signer_id', sa.Uuid(), nullable=False),
    sa.Column('signature_hash', sa.String(length=255), nullable=False),
    sa.Column('key_derivation_proof', sa.JSON(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signatures')
    op.drop_table('signature_requirements')
    op.drop_table('approval_requests')
    op.drop_table('user_shares')
    op.drop_table('contracts')
    op.drop_table('users')
    op.drop_table('threshold_schemes')
    op.drop_table('group_edges')
    op.drop_table('organization_units')
    op.drop_table('groups')
    # ### end Alembic commands ###
