"""Add authority_score to Signature

Revision ID: 8ccc6ae28483
Revises: cc0b6f9cfdcb
Create Date: 2026-01-31 14:09:50.188196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccc6ae28483'
down_revision = 'cc0b6f9cfdcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signatures', sa.Column('authority_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signatures', 'authority_score')
    # ### end Alembic commands ###
